name: Scrap KOSPI stock data and calculate RS rating all.

on:
  schedule:
    - cron: "25 8 * * 1-5"
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Run Scripts
      run: |
        ./calc-rs.py
    - name: Commits
      run: |
        git config --local user.email "dalinaum@gmail.com"
        git config --local user.name "Dalinaum"
        git add .
        git commit -m "[AUTO] Daily KOSPI RS rating"
        git push origin main
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'main'
        github_token: $
